config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root 'posts#index', as: 'home'

	get 'about' => 'pages#about', as: 'about'

	resources :posts do
	resources :comments
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :username, presence: true, length: {in: 3..25}
  validates :body, presence: true, length: {in: 5..1000}
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :author, class_name: 'User'
	has_many :comments

	self.per_page = 2

	validates :title, presence: true, length: {in: 3..25}, format: {with: /[A-Za-z0-9 \n\t]/}
	validates :body, presence: true, length: {in: 5..1000}

	scope :ordered, ->(direction = :desc) { order(created_at: direction) }
	scope :with_authors, -> { includes(:author) }
	scope :search, ->(query) do
		return if query.blank?
			where('title LIKE ? OR title LIKE ? OR body LIKE ? OR body LIKE ?', "#{query.squish}%", "% #{query.squish}%", "#{query.squish}%", "% #{query.squish}%")
	end

	scope :Filter, ->(filter) do
		if filter == 'common'
			where(theme: Post::THEMES[:common])
		elsif filter == 'sport'
			where(theme: Post::THEMES[:sport])
		elsif filter == 'science'
			where(theme: Post::THEMES[:science])
		elsif filter == 'games'
			where(theme: Post::THEMES[:games])
		elsif filter == 'technique'
			where(theme: Post::THEMES[:technique])
		end
	end

	THEMES = {
		common: 0,
		sport: 1,
		science: 2,
		games: 3,
		technique: 4
	}.with_indifferent_access.freeze

	enum theme: THEMES
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :rememberable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :validatable
  validates :email, presence: true, length: {in: 5..25}, format: {with: /[A-Za-z0-9@A-Za-z0-9]/}
  validates :username, presence: true, length: {in: 3..25}, format: {with: /[A-Za-z0-9]/}
  has_many :posts, foreign_key: :author_id, dependent: :destroy

  ROLES = {
  user: 0,
  moderator: 1,
  admin: 2,
  }.with_indifferent_access.freeze

  enum role: ROLES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit

	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}
    end

	private def user_not_authorized
		flash[:alert] = "You are not authorized to perform this action."
		redirect_to(request.referrer || root_path)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: %i[new create destroy]

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		@comment.username = current_user.username
		@comment.save
		redirect_to post_path(@post), notice: "Comment was successfully created."
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		authorize @comment
		@comment.destroy
		redirect_to post_path(@post), notice: "Comment was successfully deleted."
	end

	private def comment_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About creators page';
		@content = 'Some info about developers';
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: %i[new create edit update destroy]

	def index
		@posts = Post.ordered.with_authors.search(params[:query]).Filter(params[:filter]).paginate(page: params[:page])
		authorize Post
	end

	def show
		@post = Post.find(params[:id])
		authorize @post
	end

	def new
		@post = Post.new
		authorize Post
	end

	def create
		@post = Post.new(post_params)
		authorize Post
		@post.author = current_user
		if(@post.save)
			redirect_to @post, notice: "Post was successfully created."
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
		authorize @post
	end

	def update
		@post = Post.find(params[:id])
		authorize @post
		if(@post.update(post_params))
			redirect_to @post, notice: "Post was successfully updated."
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		authorize @post
		@post.comments.each do |comment|
			comment.destroy
		end
		@post.destroy
		redirect_to posts_path, notice: "Post was successfully deleted."
	end

	private def post_params
		params.require(:post).permit(:title, :body, :theme)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
	<% @post.comments.each do |comment| %>
		<div class='container'>
			<p>
				<strong><%= comment.username %></strong>: <%= comment.body %><br>
				<% if policy(comment).destroy? %>
					<%= link_to "Delete", [comment.post, comment], method: :delete, data: {confirm: 'Are you sure to delete comment?'}, :class => 'btn btn-outline-danger' %>
				<% end %>
			</p>
		</div><hr>
	<% end %>

app/views/comments/_form.html.erb
<h3>Add comment</h3>
	<div class="container">
		<%= form_for([@post, @post.comments.build]) do |f| %>

		<div class="mb-3">
			<%= f.label :body %>
			<%= f.text_area(:body, {:class => 'form-control', :style => 'height: 100px'}) %>
			</div>
		
		<div class="mb-3">
			<%= f.submit({:class => 'btn btn-outline-success'}) %>
		</div>
		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codegram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
    <div class="px-3 py-2 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="http://localhost:3000/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-journal-code" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8.646 5.646a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1 0 .708l-2 2a.5.5 0 0 1-.708-.708L10.293 8 8.646 6.354a.5.5 0 0 1 0-.708zm-1.292 0a.5.5 0 0 0-.708 0l-2 2a.5.5 0 0 0 0 .708l2 2a.5.5 0 0 0 .708-.708L5.707 8l1.647-1.646a.5.5 0 0 0 0-.708z"/>
                <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
            </svg>
            <span class="lead">Codegram</span>
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <span class="nav-link text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-house-fill d-block mx-auto" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                    <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                </svg>
                <%= link_to "Home", home_path, :class => "nav-link text-white" %>
              </span>
            </li>
            <li>
              <span class="nav-link text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-pencil-square d-block mx-auto" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
                <%= link_to "Create post", new_post_path, :class => "nav-link text-white" %>
              </span>
            </li>
            <li>
              <span class="nav-link text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-chat-text-fill d-block mx-auto" viewBox="0 0 16 16">
                    <path d="M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM4.5 5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-7zm0 2.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-7zm0 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4z"/>
                </svg>
                <%= link_to "Message", home_path, :class => "nav-link text-white" %>
              </span>
            </li>
            <li>
              <span class="nav-link text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-cloud-arrow-up-fill d-block mx-auto" viewBox="0 0 16 16">
                    <path d="M8 2a5.53 5.53 0 0 0-3.594 1.342c-.766.66-1.321 1.52-1.464 2.383C1.266 6.095 0 7.555 0 9.318 0 11.366 1.708 13 3.781 13h8.906C14.502 13 16 11.57 16 9.773c0-1.636-1.242-2.969-2.834-3.194C12.923 3.999 10.69 2 8 2zm2.354 5.146a.5.5 0 0 1-.708.708L8.5 6.707V10.5a.5.5 0 0 1-1 0V6.707L6.354 7.854a.5.5 0 1 1-.708-.708l2-2a.5.5 0 0 1 .708 0l2 2z"/>
                </svg>
                <%= link_to "Drive", home_path, :class => "nav-link text-white" %>
              </span>
            </li>
            <li>
              <span class="nav-link text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-info-square-fill d-block mx-auto" viewBox="0 0 16 16">
                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm8.93 4.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM8 5.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                </svg>
                <%= link_to "About", about_path, :class => "nav-link text-white" %>
              </span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="px-3 py-2 border-bottom mb-3">
      <div class="container d-flex flex-wrap justify-content-center">
        <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
          <%= form_with method: :get do |form| %>
          <div class='d-flex justify-content-between'>
            <%= form.text_field(:query, {value: params[:query], :class => 'form-control me-3', :placeholder => 'Search...'}) %>
            <%= form.submit('Search', {:class => 'btn btn-outline-dark ms-3'}) %>
          </div>
          <% end %>
        </form>

        <div class="text-end">
            <% if user_signed_in? %>
                <%= current_user.username %>
                <% if current_user.admin? %>
                    (You are admin)
                <% end %>
                <% if current_user.moderator? %>
                    (You are moderator)
                <% end %>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure to sign out?'}, :class => 'btn btn-outline-danger' %>
            <% else %>
                <%= link_to "Log in", new_user_session_path, :class => 'btn btn-light' %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-dark' %>
            <% end %>
        </div>
      </div>
    </div>
    </header>

    <div class="container rounded">
        <p class="notice text-success"><%= notice %></p>
        <p class="alert text-danger"><%= alert %></p>
        <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container bg-light p-5 col-md-8 mx-auto rounded">
	<h1><%= @title%></h1>
	<div class="container">
		<p><%= @content%></p>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="container bg-light p-5 col-md-8 mx-auto">
    <h1>Edit Post</h1>
	<div class="container">
    <%= form_for :post, url: post_path(@post), method: :patch do |form| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
      <div class="mb-3">
        <%= form.label :title %>
        <%= form.text_field(:title, {:class => 'form-control'}) %>
      </div>
		<div class="mb-3">
			<%= form.label :theme %>
			<%= form.select :theme, ['common', 'sport', 'science', 'games', 'technique'], selected: 'common', class: "form-select"%>
		</div>
		<div class="mb-3">
        <%= form.label :body %>
        <%= form.text_area(:body, {:class => 'form-control', :style => 'height: 200px'}) %>
	</div>

      <div class="mb-3">
        <%= form.submit('Edit Post' ,{:class => 'btn btn-outline-success'}) %>
      </div>
    </div>
	<% end %>
</div>

app/views/posts/index.html.erb
<div class="container bg-light p-5 col-md-8 mx-auto rounded">
	<h1>Codegram</h1>
	<%= form_with method: :get do |form| %>
	<div class='d-flex justify-content-between'>
		<%= form.select(:filter, ['common', 'sport', 'science', 'games', 'technique'], {value: params[:filter], :class => 'form-control me-3', :placeholder => 'Category...'}) %>
		<%= form.submit('Filter', {:class => 'btn btn-outline-dark ms-3'}) %>
	</div>
	<% end %>
		<br>
		<% @posts.each do |post| %>
	<a class="text-decoration-none text-dark" href ="<%= post_path(post) %>">
		<div class="container rounded border border-secondary">
			<h3><%= post.title %></h3>
			<h6><%= post.theme %></h6>
			<p style="text-align: justify;"><%= post.body %></p>
			<h6>by <%= post.author.username %></h6>
		</div><br>
	</a>
	<% end %>
	<div class="apple_pagination justify-content-center d-flex">
		<div class="page_info">
			<%= will_paginate(@posts) %>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container bg-light p-5 col-md-8 mx-auto rounded">
    <h1>New Post</h1>
	<div class="container">
    <%= form_for :post, url: posts_path do |form| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
      <div class="mb-3">
        <%= form.label :title %>
        <%= form.text_field(:title, {:class => 'form-control'}) %>
      </div>
	    <div class="mb-3">
			<%= form.label :theme %>
			<%= form.select :theme, ['common', 'sport', 'science', 'games', 'technique'], selected: 'common', class: "form-select"%>
		</div>
		<div class="mb-3">
        <%= form.label :body %>
        <%= form.text_area(:body, {:class => 'form-control', :style => 'height: 200px'}) %>
		</div>

      <div class="mb-3">
        <%= form.submit('Add Post' ,{:class => 'btn btn-outline-success'}) %>
		</div>
    </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="container bg-light p-5 col-md-8 mx-auto rounded">
	<h2><%= @post.title%></h2>
	<h6><%= @post.theme %></h6>
	<div class="container">
		<p style="text-align: justify;"><%= @post.body%></p>
		<h6>by <%= @post.author.username %></h6><hr>
		<% if policy(@post).update? %>
			<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-outline-warning' %>
		<% end %>
		<% if policy(@post).destroy? %>
			<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: 'Are you sure to delete post?'}, :class => 'btn btn-outline-danger' %>
		<% end %>
		<br><br>
		<%= render 'comments/comments' %>
	</div>
		<% if policy(@post).login? %>
			<%= render 'comments/form' %>
		<% end %>
</div>